/**
 * auth.js — stateless admin sessions.
 *
 * A signed, httpOnly cookie carries `expiry.email.hmac`. Nothing is stored
 * server-side, so restarts don't log the owner out and there is no session
 * store to scale. Rotating SESSION_SECRET invalidates every session.
 */

const crypto = require('crypto');

const SECRET = process.env.SESSION_SECRET || 'dev-only-insecure-secret';
const COOKIE = 'koydam_admin';
const SESSION_MS = (Number(process.env.SESSION_HOURS) || 12) * 60 * 60 * 1000;

function sign(value) {
  return crypto.createHmac('sha256', SECRET).update(value).digest('base64url');
}

function issueToken(email) {
  const payload = `${Date.now() + SESSION_MS}.${Buffer.from(email).toString('base64url')}`;
  return `${payload}.${sign(payload)}`;
}

function verifyToken(token) {
  if (!token || typeof token !== 'string') return null;
  const parts = token.split('.');
  if (parts.length !== 3) return null;
  const payload = `${parts[0]}.${parts[1]}`;
  const expected = sign(payload);
  const given = parts[2];
  // Length check first: timingSafeEqual throws on mismatched buffer lengths.
  if (given.length !== expected.length) return null;
  if (!crypto.timingSafeEqual(Buffer.from(given), Buffer.from(expected))) return null;
  if (Number(parts[0]) < Date.now()) return null;
  return { email: Buffer.from(parts[1], 'base64url').toString('utf8') };
}

/** Minimal cookie header parser — avoids a cookie-parser dependency. */
function parseCookies(header) {
  const out = {};
  (header || '').split(';').forEach((pair) => {
    const idx = pair.indexOf('=');
    if (idx < 0) return;
    out[pair.slice(0, idx).trim()] = decodeURIComponent(pair.slice(idx + 1).trim());
  });
  return out;
}

function setSessionCookie(res, token) {
  const secure = process.env.NODE_ENV === 'production' ? ' Secure;' : '';
  res.setHeader('Set-Cookie',
    `${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax;${secure} Max-Age=${Math.floor(SESSION_MS / 1000)}`);
}

function clearSessionCookie(res) {
  res.setHeader('Set-Cookie', `${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0`);
}

/**
 * Cleans a hash as it arrives from the environment.
 *
 * Hosting panels mangle long values in predictable ways: they wrap them in
 * quotes, keep the trailing newline, or soft-wrap the field and store the line
 * break. All of that is recoverable — the hash is hex plus one colon, so any
 * whitespace inside it is noise.
 */
function normaliseHash(value) {
  return String(value || '')
    .trim()
    .replace(/^["']|["']$/g, '')
    .replace(/\s+/g, '');
}

/** Valid digest lengths in hex chars: 32-byte (default) and 64-byte (legacy). */
const DIGEST_LENGTHS = { 64: 32, 128: 64 };

/** Describes what is wrong with a stored hash, or null when it is usable. */
function inspectHash(value) {
  const hash = normaliseHash(value);
  if (!hash) return { ok: false, length: 0, problem: 'empty' };
  if (!hash.includes(':')) return { ok: false, length: hash.length, problem: 'no-separator' };

  const [salt, digest] = hash.split(':');
  if (salt.length !== 32) return { ok: false, length: hash.length, problem: 'bad-salt' };
  if (!DIGEST_LENGTHS[digest.length]) return { ok: false, length: hash.length, problem: 'bad-digest' };
  if (!/^[0-9a-f]+$/i.test(salt + digest)) return { ok: false, length: hash.length, problem: 'not-hex' };

  return { ok: true, length: hash.length, hash };
}

/**
 * scrypt hash, stored as `salt:digest` in ADMIN_PASSWORD_HASH.
 * 32 bytes by default — 97 characters total, short enough to survive the
 * value-length limits some hosting panels impose on environment variables.
 */
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex'), keylen = 32) {
  const derived = crypto.scryptSync(password, salt, keylen).toString('hex');
  return `${salt}:${derived}`;
}

function checkPassword(password, stored) {
  const info = inspectHash(stored);
  if (!info.ok) return false;

  const [salt, digest] = info.hash.split(':');
  // Key length comes from the stored digest, so hashes generated by any
  // previous version keep working.
  const derived = crypto.scryptSync(password, salt, DIGEST_LENGTHS[digest.length]).toString('hex');
  if (derived.length !== digest.length) return false;
  return crypto.timingSafeEqual(Buffer.from(derived), Buffer.from(digest));
}

/** True when the server has any admin credential configured at all. */
function credentialsConfigured() {
  return Boolean(process.env.ADMIN_PASSWORD_HASH || process.env.ADMIN_PASSWORD);
}

/**
 * Authenticates an admin login.
 *
 * Returns { ok, reason } rather than a bare boolean so the caller can log
 * precisely why a login failed. The reason is for the server log only — the
 * HTTP response stays deliberately vague, except for `not-configured`, where
 * there is no security to protect and the operator needs to be told.
 */
function authenticate(email, password) {
  if (!credentialsConfigured()) return { ok: false, reason: 'not-configured' };

  const configured = process.env.ADMIN_EMAIL || 'hello@koydam.com';
  const adminEmail = configured.trim().replace(/^["']|["']$/g, '').toLowerCase();
  const given = String(email || '').trim().toLowerCase();

  if (given !== adminEmail) return { ok: false, reason: 'email-mismatch' };

  if (process.env.ADMIN_PASSWORD_HASH) {
    const info = inspectHash(process.env.ADMIN_PASSWORD_HASH);
    if (info.ok) {
      return checkPassword(password, info.hash)
        ? { ok: true }
        : { ok: false, reason: 'password-mismatch' };
    }
    // An unusable hash locks the owner out entirely. If a plaintext password is
    // also configured, prefer it over failing: the intent is obvious, and being
    // locked out of your own site is the worse outcome.
    if (!process.env.ADMIN_PASSWORD) {
      return { ok: false, reason: 'hash-malformed', detail: info };
    }
  }

  const plain = process.env.ADMIN_PASSWORD;
  const a = Buffer.from(String(password));
  const b = Buffer.from(plain);
  const match = a.length === b.length && crypto.timingSafeEqual(a, b);
  return match ? { ok: true } : { ok: false, reason: 'password-mismatch' };
}

/** Backwards-compatible boolean wrapper. */
const verifyCredentials = (email, password) => authenticate(email, password).ok;

/**
 * Logged once at boot. A server with no credentials configured rejects every
 * login attempt, and silently doing so is the hardest failure to diagnose.
 */
function warnIfMisconfigured() {
  if (!credentialsConfigured()) {
    console.warn('┌──────────────────────────────────────────────────────────────┐');
    console.warn('│  ADMIN LOGIN IS DISABLED                                     │');
    console.warn('│  Neither ADMIN_PASSWORD_HASH nor ADMIN_PASSWORD is set, so   │');
    console.warn('│  every login attempt will fail. Set ADMIN_PASSWORD_HASH in   │');
    console.warn('│  your environment, then restart. Generate one with:          │');
    console.warn('│    node server/scripts/hash-password.js "your password"      │');
    console.warn('└──────────────────────────────────────────────────────────────┘');
  } else if (process.env.ADMIN_PASSWORD_HASH) {
    const info = inspectHash(process.env.ADMIN_PASSWORD_HASH);
    if (!info.ok) {
      const source = require('./env').sourceOf('ADMIN_PASSWORD_HASH');
      console.warn(`[auth] ADMIN_PASSWORD_HASH is unusable: ${info.problem} (${info.length} characters stored).`);
      console.warn(`[auth] The value came from ${source} — correct it there.`);
      console.warn('[auth] Expected 97 characters: 32-char salt, a colon, then a 64-char digest.');
      if (info.length === 13) {
        console.warn('[auth] A 13-character value is usually the password itself, not its hash.');
      }
      console.warn('[auth] Regenerate with: node server/scripts/hash-password.js "your password"');
    }
  }

  if (process.env.ADMIN_PASSWORD) {
    const shadowed = process.env.ADMIN_PASSWORD_HASH && inspectHash(process.env.ADMIN_PASSWORD_HASH).ok;
    if (shadowed) {
      console.warn('[auth] Both ADMIN_PASSWORD_HASH and ADMIN_PASSWORD are set. '
        + 'The hash wins — remove it if you meant to use the plaintext password.');
    } else {
      console.log('[auth] Using ADMIN_PASSWORD (plaintext). Anyone who can read your '
        + 'hosting configuration can read this password.');
    }
  }

  if (!process.env.SESSION_SECRET) {
    console.warn('[auth] SESSION_SECRET is not set — sessions will not survive a restart.');
  }
}

/** Express middleware: 401s API calls, redirects page requests to /admin/login. */
function requireAuth(req, res, next) {
  const cookies = parseCookies(req.headers.cookie);
  const session = verifyToken(cookies[COOKIE]);
  if (!session) {
    // originalUrl, not path: inside a mounted router req.path is router-relative,
    // so /api/admin/content would otherwise be treated as a page request.
    if (req.originalUrl.startsWith('/api/')) return res.status(401).json({ error: 'Not authenticated' });
    return res.redirect('/admin/login.html');
  }
  req.session = session;
  next();
}

module.exports = {
  COOKIE, issueToken, verifyToken, parseCookies, setSessionCookie,
  clearSessionCookie, hashPassword, checkPassword, verifyCredentials, requireAuth,
  authenticate, credentialsConfigured, warnIfMisconfigured, inspectHash, normaliseHash,
};
